spring.application.name=rentalBusiness

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/rentalBusiness?useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username = root
spring.datasource.password =
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
server.port = 23990
logging.level.org.springframework.security=DEBUG

flutterwave.secretKey=FLWSECK_TEST-d52b1bf1130312b16a4930cb24edcfff-X
flutterwave.secretHash=sfpmqosoafidfvy
# flutterwave.publicKey=FLWPUBK_TEST-39a6ab7d77f3440d4b2649b38554a5c1-X
